//! Build-time helpers for compiling brand icon resources into Windows binaries.
//!
//! This module is a **build-script companion**, not a runtime library. The
//! public functions and constants here are intended to be called from a
//! consuming crate's `build.rs`, not from `fn main`.
//!
//! The intent is to replace the historical per-app `winres 0.1` boilerplate
//! (which mangles PNG-compressed multi-size ICOs) with the official Microsoft
//! `embed-resource` 2.x crate, while letting the local76 brand defaults
//! (`ProductName="local76 Suite"`, `CompanyName="local76"`, etc.) be
//! shared across every tool in the ecosystem from one place.
//!
//! See `docs/VISUAL_STANDARDS.md` for the spec and `docs/ICON_TROUBLESHOOTING.md`
//! for the verifier recipe.
//!
//! # Usage in a consuming crate
//!
//! The `embed-resource` 2.x crate takes a `.rc` resource script, not an
//! ICO directly. The `build_resources` module writes one `.rc` next to
//! each binary and points `embed_resource::compile` at it.
//!
//! In the consuming crate's `Cargo.toml`:
//! ```toml
//! [build-dependencies]
//! embed-resource = "2"
//! ```
//!
//! In its `build.rs`:
//! ```ignore
//! use std::path::Path;
//! use library::build_resources::{write_brand_rc, DEFAULT_COMPANY_NAME, DEFAULT_LEGAL_COPYRIGHT, DEFAULT_PRODUCT_NAME};
//!
//! fn main() {
//!     let ico = "assets/icon.ico";
//!     if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") { return; }
//!     if !Path::new(ico).exists() { return; }
//!
//!     // The cargo_pkg_name is used as FileDescription fallback
//!     let pkg = std::env::var("CARGO_PKG_NAME").unwrap_or_default();
//!     let rc = write_brand_rc(
//!         "build/windows_resource.rc",
//!         ico,
//!         &pkg,                       // FileDescription
//!         DEFAULT_PRODUCT_NAME,
//!         DEFAULT_COMPANY_NAME,
//!         DEFAULT_LEGAL_COPYRIGHT,
//!     );
//!     embed_resource::compile(&rc, embed_resource::NONE);
//! }
//! ```

use std::path::Path;

pub mod rc_split;

pub use rc_split::split_for_rc;

/// Default product name baked into every local76 tool's PE resources.
pub const DEFAULT_PRODUCT_NAME: &str = "local76 Suite";

/// Default company name baked into every local76 tool's PE resources.
pub const DEFAULT_COMPANY_NAME: &str = "local76";

/// Default legal copyright baked into every local76 tool's PE resources.
pub const DEFAULT_LEGAL_COPYRIGHT: &str = "Copyright \u{00A9} 2026 local76";

/// Generate a `windows_resource.rc` file at `out_path` (relative to
/// `CARGO_MANIFEST_DIR`) that declares the 4-size `icon.ico` plus the
/// local76 standard VERSIONINFO block, and emit a
/// `cargo:rerun-if-changed` for the ICO so the build re-runs on
/// asset changes.
///
/// Returns the absolute path to the written `.rc` file, suitable for
/// passing straight to `embed_resource::compile`.
///
/// The `.rc` format follows the syntax accepted by both `windres`
/// (GNU) and `rc.exe` (MSVC), so this works regardless of the
/// toolchain `embed-resource` selects.
pub fn write_brand_rc(
    out_path: impl AsRef<Path>,
    ico_path: &str,
    file_description: &str,
    product_name: &str,
    company_name: &str,
    legal_copyright: &str,
) -> String {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_default();
    let out_abs = if out_path.as_ref().is_absolute() {
        out_path.as_ref().to_path_buf()
    } else {
        Path::new(&manifest_dir).join(out_path.as_ref())
    };

    // Workaround for Windows SDK rc.exe 10.0+ ICONDIR corruption bug:
    // rc.exe mangles multi-size ICOs declared via `1 ICON "path.ico"`. We
    // split the ICO into 4 single-size files and emit 4 separate ICON
    // directives instead, which rc.exe handles correctly.
    let split = split_for_rc(ico_path);
    let ico_block: String = if !split.is_empty() {
        let mut s = String::new();
        for (id, path) in &split {
            let p = path.to_string_lossy().replace('\\', "/");
            s.push_str(&format!("{id} ICON \"{p}\"\n"));
        }
        s
    } else {
        // Linux / no split path — single ICON directive
        let ico_abs = if Path::new(ico_path).is_absolute() {
            ico_path.to_string()
        } else {
            Path::new(&manifest_dir)
                .join(ico_path)
                .to_string_lossy()
                .replace('\\', "\\\\")
        };
        format!("1 ICON \"{ico_abs}\"\n")
    };

    let rc = format!(
        r#"// Auto-generated by library::build_resources::write_brand_rc
// Do not edit by hand; rerun cargo to regenerate.

{ico_block}
1 VERSIONINFO
FILEVERSION 1,0,0,0
PRODUCTVERSION 1,0,0,0
BEGIN
    BLOCK "StringFileInfo"
    BEGIN
        BLOCK "040904E4"
        BEGIN
            VALUE "CompanyName",     "{company}\0"
            VALUE "FileDescription", "{file_desc}\0"
            VALUE "LegalCopyright",  "{copyright}\0"
            VALUE "ProductName",     "{product}\0"
        END
    END
    BLOCK "VarFileInfo"
    BEGIN
        VALUE "Translation", 0x0409, 1252
    END
END
"#,
        company = escape_rc(company_name),
        file_desc = escape_rc(file_description),
        copyright = escape_rc(legal_copyright),
        product = escape_rc(product_name),
    );

    if let Some(parent) = out_abs.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    std::fs::write(&out_abs, rc).expect("failed to write windows_resource.rc");
    println!("cargo:rerun-if-changed={}", ico_path);

    out_abs.to_string_lossy().to_string()
}

/// Escape a string for inclusion inside a double-quoted RC `VALUE`.
/// Strips characters that would terminate the literal.
fn escape_rc(s: &str) -> String {
    s.replace('"', "'").replace('\n', " ")
}
